#pragma once

#include "resource.h"

#define NID_UID 123
#define WM_TASKBARNOTIFY WM_USER+20
#define WM_TASKBARNOTIFY_MENUITEM_SHOW (WM_USER + 21)
#define WM_TASKBARNOTIFY_MENUITEM_HIDE (WM_USER + 22)
#define WM_TASKBARNOTIFY_MENUITEM_RELOAD (WM_USER + 23)
#define WM_TASKBARNOTIFY_MENUITEM_ABOUT (WM_USER + 24)
#define WM_TASKBARNOTIFY_MENUITEM_EXIT (WM_USER + 25)
#define WM_TASKBARNOTIFY_MENUITEM_PROXYLIST_BASE (WM_USER + 26)

#define WM_TASKBARNOTIFY_MENUITEM_STARTUP (WM_USER + 10)
#define WM_TASKBARNOTIFY_MENUITEM_OPENURL (WM_USER + 11)
#define WM_TASKBARNOTIFY_MENUITEM_ELEVATE (WM_USER + 12)
#define WM_TASKBARNOTIFY_MENUITEM_HIDEALL (WM_USER + 13)
#define WM_TASKBARNOTIFY_MENUITEM_DISABLEALL (WM_USER + 14)
#define WM_TASKBARNOTIFY_MENUITEM_ENABLEALL (WM_USER + 15)
#define WM_TASKBARNOTIFY_MENUITEM_SHOWALL (WM_USER + 16)

#define WM_HOTKEY_ID_BASE (WM_USER + 60)
#define WM_HOTKEY_LEFT_CLICK (WM_USER + 61)
#define WM_HOTKEY_RIGHT_CLICK (WM_USER + 62)
#define WM_HOTKEY_ADD_ALPHA (WM_USER + 63)
#define WM_HOTKEY_MINUS_ALPHA (WM_USER + 64)
#define WM_HOTKEY_TOPMOST (WM_USER + 65)
